name: mandatory check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,maxOS-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install pylint and black
      run: |
        python -m pip install --upgrade pip
        pip install pylint black

    - name: Run black on Python files
      run: |
        black . --check

    - name: Run pylint on Python files
      run: |
        pylint $(find . -name "*.py") --max-score=10 --output-format=text > pylint_report.txt
        SCORE=$(tail -n 1 pylint_report.txt | awk '{print $1}')
        if (( $(echo "$SCORE < 8.9" |bc -l) )); then
          echo "Pylint score is less than 8.9. Please fix the issues." && exit 1
        fi

    - name: Run make command
      run: make format
