name: mandatory check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,maxOS-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies if not already installed
      run: |
        if ! pip show black > /dev/null 2>&1; then
          echo "Installing black..."
          pip install black
        else
          echo "Black is already installed."
        fi

        if ! pip show pylint > /dev/null 2>&1; then
          echo "Installing pylint..."
          pip install pylint
        else
          echo "Pylint is already installed."
        fi

    - name: Run make command
      run: make format

    - name: Run pylint on Python files
      run: |
        pylint $(find . -name "*.py") --max-score=10 --output-format=text > pylint_report.txt
        SCORE=$(tail -n 1 pylint_report.txt | awk '{print $1}')
        if (( $(echo "$SCORE < 8.9" |bc -l) )); then
          echo "Pylint score is less than 8.9. Please fix the issues." && exit 1
        fi
